Update

diff --git a/.github/workflows/emerge-1-installed.yml b/.github/workflows/emerge-1-installed.yml
--- a/.github/workflows/emerge-1-installed.yml
+++ b/.github/workflows/emerge-1-installed.yml
@@ -41,6 +41,13 @@ jobs:
         run: |
           # Download, extract, and clean up the Gentoo stage3 tarball
           wget --directory-prefix=/tmp/ --no-verbose http://mirror.rackspace.com/gentoo/releases/amd64/autobuilds/$STAGE_3_DATE/stage3-amd64-desktop-systemd-$STAGE_3_DATE.tar.xz
+          wget --directory-prefix=/tmp/ --no-verbose https://distfiles.gentoo.org/releases/amd64/autobuilds/$STAGE_3_DATE/stage3-amd64-desktop-systemd-$STAGE_3_DATE.tar.xz.sha256
+          sha256sum --check stage3-amd64-desktop-systemd-$STAGE_3_DATE.tar.xz.sha256
+          if [ $? -ne 0 ]; then
+            echo "Checksum verification failed"
+            exit 1
+          fi
+          rm stage3-amd64-desktop-systemd-$STAGE_3_DATE.tar.xz.sha256
           sudo mkdir /var/lib/gentoo
           sudo tar --directory=/var/lib/gentoo/ --extract --file /tmp/stage3-amd64-desktop-systemd-$STAGE_3_DATE.tar.xz --numeric-owner --preserve-permissions --xattrs-include='*.*'
           rm /tmp/stage3-amd64-desktop-systemd-$STAGE_3_DATE.tar.xz
